function FileData_Pairs(x)
{
x.t("creation","management");
x.t("managing","lists");
x.t("lists","lists");
x.t("lists","reporter");
x.t("lists","list");
x.t("lists","gene");
x.t("lists","further");
x.t("lists","function");
x.t("refine","queries");
x.t("reporter","gene");
x.t("list","management");
x.t("overview","managing");
x.t("overview","list");
x.t("overview","manage");
x.t("gene","lists");
x.t("centralizes","activities");
x.t("patientdid","lists");
x.t("further","refine");
x.t("study-defined","patientdid");
x.t("queries","facilitate");
x.t("function","centralizes");
x.t("user-defined","study-defined");
x.t("pertaining","creation");
x.t("facilitate","analysis");
x.t("activities","pertaining");
x.t("management","overview");
x.t("management","user-defined");
x.t("manage","lists");
}
