function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","designed");
x.t("lists","reporter");
x.t("lists","list");
x.t("lists","gene");
x.t("lists","include");
x.t("sidebar","contains");
x.t("providing","sets");
x.t("cma","portal");
x.t("designed","facilitate");
x.t("reporter","gene");
x.t("list","types");
x.t("gene","lists");
x.t("gene","names");
x.t("patientdid","lists");
x.t("sets","predefined");
x.t("portal","sidebar");
x.t("number","lists");
x.t("types","managing");
x.t("types","cma");
x.t("types","list");
x.t("include","patientdid");
x.t("facilitate","analysis");
x.t("data","elements");
x.t("patient","gene");
x.t("predefined","data");
x.t("elements","patient");
x.t("analysis","providing");
x.t("names","lists");
x.t("contains","number");
}
