function FileData_Pairs(x)
{
x.t("workspaces","workspace");
x.t("home","page");
x.t("navigating","cancer");
x.t("cma","portal");
x.t("getting","started");
x.t("access","workspaces");
x.t("investigate","genomic");
x.t("started","cancer");
x.t("allow","investigate");
x.t("cancer","molecular");
x.t("quick","access");
x.t("portal","home");
x.t("portal","navigating");
x.t("portal","getting");
x.t("portal","panes");
x.t("workspace","tools");
x.t("enable","quick");
x.t("tools","resources");
x.t("page","enable");
x.t("panes","cma");
x.t("molecular","analysis");
x.t("analysis","portal");
x.t("genomic","data");
x.t("resources","allow");
}
