function FileData_Pairs(x)
{
x.t("available","tcga");
x.t("depictions","pathways");
x.t("currently","available");
x.t("working","gene-based");
x.t("working","pathways");
x.t("anomalies","working");
x.t("anomalies","feature");
x.t("link","gene");
x.t("access","graphic");
x.t("agents","anomalies");
x.t("gene-based","views");
x.t("gene","view");
x.t("tcga","context");
x.t("visualizing","pathways");
x.t("provides","access");
x.t("provides","detailed");
x.t("visualization","link");
x.t("feature","currently");
x.t("workspace","provides");
x.t("detailed","information");
x.t("interest","provides");
x.t("pathways","working");
x.t("pathways","visualizing");
x.t("pathways","interest");
x.t("pathways","associated");
x.t("pathways","pathway");
x.t("view","workspace");
x.t("graphic","depictions");
x.t("information","associated");
x.t("genes","agents");
x.t("associated","anomalies");
x.t("associated","genes");
x.t("views","visualizing");
x.t("pathway","visualization");
}
