function FileData_Pairs(x)
{
x.t("workspaces","tabs");
x.t("navigating","cancer");
x.t("getting","started");
x.t("access","cmap");
x.t("top","workspace");
x.t("cmap","workspaces");
x.t("features","getting");
x.t("features","tabs");
x.t("started","cancer");
x.t("allow","access");
x.t("cancer","molecular");
x.t("portal","workspaces");
x.t("portal","navigating");
x.t("workspace","allow");
x.t("run","across");
x.t("tabs","features");
x.t("tabs","run");
x.t("across","top");
x.t("molecular","analysis");
x.t("analysis","portal");
}
