function FileData_Pairs(x)
{
x.t("available","tcga");
x.t("depictions","pathways");
x.t("currently","available");
x.t("working","pathways");
x.t("anomalies","feature");
x.t("anomalies","pathway");
x.t("access","graphic");
x.t("agents","anomalies");
x.t("overview","working");
x.t("overview","pathway");
x.t("gene","view");
x.t("tcga","context");
x.t("provides","access");
x.t("provides","detailed");
x.t("visualization","overview");
x.t("visualization","section");
x.t("feature","currently");
x.t("workspace","provides");
x.t("detailed","information");
x.t("section","gene");
x.t("interest","provides");
x.t("pathways","interest");
x.t("pathways","associated");
x.t("view","workspace");
x.t("graphic","depictions");
x.t("information","associated");
x.t("genes","agents");
x.t("associated","anomalies");
x.t("associated","genes");
x.t("pathway","visualization");
}
