function FileData_Pairs(x)
{
x.t("describes","cancer");
x.t("generating","pathway");
x.t("diagrams","investigating");
x.t("working","pathways");
x.t("anomalies","tables");
x.t("anomalies","working");
x.t("anomalies","section");
x.t("anomalies","associated");
x.t("investigating","genes");
x.t("overview","generating");
x.t("gene","anomalies");
x.t("via","pathway");
x.t("cancer","molecular");
x.t("portal","review");
x.t("review","pathways");
x.t("visualization","overview");
x.t("section","describes");
x.t("section","include");
x.t("pathways","anomalies");
x.t("pathways","associated");
x.t("include","pathway");
x.t("genes","via");
x.t("topics","section");
x.t("associated","anomalies");
x.t("associated","topics");
x.t("molecular","analysis");
x.t("analysis","portal");
x.t("pathway","diagrams");
x.t("pathway","gene");
x.t("pathway","visualization");
}
