function FileData_Pairs(x)
{
x.t("pattern","analysis");
x.t("access","broad");
x.t("gene","pattern");
x.t("analyze","genomic");
x.t("enables","select");
x.t("provides","access");
x.t("methods","used");
x.t("array","platform");
x.t("array","computational");
x.t("patients","genes");
x.t("select","groups");
x.t("groups","patients");
x.t("broad","array");
x.t("tools","gene");
x.t("platform","data");
x.t("tool","enables");
x.t("genes","array");
x.t("data","criteria");
x.t("application","genepattern");
x.t("genepattern","provides");
x.t("genepattern","application");
x.t("used","analyze");
x.t("criteria","analysis");
x.t("analysis","gene");
x.t("analysis","tools");
x.t("analysis","tool");
x.t("analysis","genepattern");
x.t("analysis","analysis");
x.t("computational","methods");
x.t("genomic","data");
}
