function FileData_Pairs(x)
{
x.t("available","currently");
x.t("managing","lists");
x.t("lists","available");
x.t("lists","managing");
x.t("lists","create");
x.t("lists","reporter");
x.t("lists","list");
x.t("lists","queries");
x.t("create","custom");
x.t("currently","however");
x.t("however","define");
x.t("reporter","gene");
x.t("list","types");
x.t("gene","lists");
x.t("custom","lists");
x.t("custom","reporter");
x.t("queries","predefined");
x.t("define","custom");
x.t("types","reporter");
x.t("predefined","reporter");
}
