function FileData_Pairs(x)
{
x.t("instructions","provided");
x.t("provided","application");
x.t("access","cancer");
x.t("direct","access");
x.t("provides","direct");
x.t("cancer","genome");
x.t("follow","instructions");
x.t("conduct","study");
x.t("workbench","cancer");
x.t("workbench","website");
x.t("workbench","tool");
x.t("workbench","application");
x.t("workbench","analysis");
x.t("website","conduct");
x.t("tools","cancer");
x.t("help","cancer");
x.t("tool","provides");
x.t("application","follow");
x.t("application","help");
x.t("genome","workbench");
x.t("analysis","tools");
}
