function FileData_Pairs(x)
{
x.t("method","identifying");
x.t("pattern","recognition");
x.t("highlighting","patterns");
x.t("differences","pca");
x.t("meaningful","terms");
x.t("component","analysis");
x.t("display","meaningful");
x.t("pca","algorithms");
x.t("number","dimensions");
x.t("finding","similarities");
x.t("purpose","finding");
x.t("algorithms","compress");
x.t("compress","number");
x.t("principal","component");
x.t("identifying","highlighting");
x.t("visual","display");
x.t("tools","principal");
x.t("(pca)","method");
x.t("dimensions","data");
x.t("data","purpose");
x.t("data","visual");
x.t("similarities","differences");
x.t("terms","pattern");
x.t("analysis","principal");
x.t("analysis","tools");
x.t("analysis","(pca)");
x.t("analysis","analysis");
x.t("patterns","data");
}
