function FileData_Pairs(x)
{
x.t("working","pca");
x.t("displays","results");
x.t("sample","sample");
x.t("sample","group");
x.t("group","color-coded");
x.t("results","query");
x.t("enables","find");
x.t("component","analysis");
x.t("find","main");
x.t("point","graph");
x.t("pca","enables");
x.t("pca","plots");
x.t("represents","sample");
x.t("multi-dimensional","data");
x.t("principal","component");
x.t("tools","principal");
x.t("main","dimensions");
x.t("(pca)","plot");
x.t("dimensions","variation");
x.t("variation","multi-dimensional");
x.t("query","pca");
x.t("data","point");
x.t("graph","represents");
x.t("plots","working");
x.t("plots","principal");
x.t("plots","analysis");
x.t("plot","displays");
x.t("analysis","working");
x.t("analysis","tools");
x.t("analysis","(pca)");
}
