function FileData_Pairs(x)
{
x.t("study","data");
x.t("study","clinical");
x.t("sample-based","plots");
x.t("describes","cancer");
x.t("explore","relationships");
x.t("working","clinical");
x.t("creating","sample-based");
x.t("search","criteria");
x.t("cancer","molecular");
x.t("portal","study");
x.t("section","describes");
x.t("section","include");
x.t("reports","creating");
x.t("include","specifying");
x.t("specifying","clinical");
x.t("data","explore");
x.t("data","search");
x.t("data","topics");
x.t("topics","section");
x.t("relationships","clinical");
x.t("criteria","working");
x.t("molecular","study");
x.t("molecular","analysis");
x.t("analysis","portal");
x.t("views","working");
x.t("views","section");
x.t("clinical","reports");
x.t("clinical","data");
x.t("clinical","molecular");
x.t("clinical","views");
}
