function FileData_Pairs(x)
{
x.t("probe","details");
x.t("probe","gene");
x.t("probe","sets");
x.t("probe","interest");
x.t("available","via");
x.t("legend","available");
x.t("legend","working");
x.t("legend","visualizing");
x.t("legend","detailed");
x.t("working","gene-based");
x.t("displays","details");
x.t("cma","reporter");
x.t("cma","viewer");
x.t("details","click");
x.t("reporter","view");
x.t("gene-based","views");
x.t("gene","expression");
x.t("via","cma");
x.t("visualizing","probe");
x.t("creating","gene");
x.t("sets","legend");
x.t("viewer","displays");
x.t("detailed","information");
x.t("interest","cma");
x.t("mean","gene");
x.t("click","probe");
x.t("geometric","mean");
x.t("view","probe");
x.t("expression","plots");
x.t("expression","plot");
x.t("information","probe");
x.t("plots","visualizing");
x.t("plots","understanding");
x.t("understanding","geometric");
x.t("plot","legend");
x.t("views","creating");
}
