function FileData_Pairs(x)
{
x.t("refer","documentation");
x.t("working","genome");
x.t("provided","genome");
x.t("browser","access");
x.t("browser","https://cgwb.nci.nih.gov/goldenpath/help/hgtrackshelp.html");
x.t("link","assistance");
x.t("link","cancer");
x.t("access","cancer");
x.t("assistance","using");
x.t("direct","link");
x.t("provides","direct");
x.t("mutation","data");
x.t("cancer","genome");
x.t("viewing","mutation");
x.t("workspace","provides");
x.t("click","cancer");
x.t("documentation","provided");
x.t("workbench","refer");
x.t("workbench","browser");
x.t("workbench","mutation");
x.t("workbench","genomic");
x.t("view","link");
x.t("view","workspace");
x.t("data","working");
x.t("data","viewing");
x.t("data","click");
x.t("data","genomic");
x.t("using","cancer");
x.t("genome","workbench");
x.t("genome","views");
x.t("views","viewing");
x.t("genomic","view");
}
