function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","editing");
x.t("lists","creating");
x.t("lists","section");
x.t("lists","topics");
x.t("describes","manage");
x.t("editing","application-defined");
x.t("new","custom");
x.t("list","types");
x.t("list","management");
x.t("gene","lists");
x.t("overview","list");
x.t("creating","new");
x.t("creating","custom");
x.t("custom","lists");
x.t("viewing","managing");
x.t("section","describes");
x.t("section","include");
x.t("types","viewing");
x.t("and/or","gene");
x.t("include","list");
x.t("application-defined","lists");
x.t("patient","and/or");
x.t("topics","section");
x.t("manage","patient");
x.t("management","overview");
}
