function FileData_Pairs(x)
{
x.t("heatmap","viewer");
x.t("pattern","analyses");
x.t("pattern","analysis");
x.t("describes","cancer");
x.t("home","integrated");
x.t("access","associated");
x.t("gene","pattern");
x.t("overview","principal");
x.t("perform","principal");
x.t("component","gene");
x.t("component","analysis");
x.t("cancer","genome");
x.t("cancer","molecular");
x.t("portal","perform");
x.t("viewer","cancer");
x.t("section","describes");
x.t("section","include");
x.t("analyses","access");
x.t("principal","component");
x.t("include","overview");
x.t("tools","section");
x.t("tools","analysis");
x.t("topics","section");
x.t("applications","topics");
x.t("genepattern","home");
x.t("genome","workbench");
x.t("analysis","gene");
x.t("analysis","portal");
x.t("analysis","tools");
x.t("analysis","applications");
x.t("analysis","genepattern");
x.t("molecular","analysis");
x.t("associated","analysis");
x.t("integrated","heatmap");
}
