function FileData_Pairs(x)
{
x.t("available","research");
x.t("home","page");
x.t("introduction","workspace");
x.t("navigating","cancer");
x.t("getting","started");
x.t("overview","pane");
x.t("features","getting");
x.t("features","overview");
x.t("features","verview");
x.t("provides","brief");
x.t("started","cancer");
x.t("cancer","molecular");
x.t("portal","home");
x.t("portal","navigating");
x.t("workspace","tools");
x.t("brief","introduction");
x.t("tools","resources");
x.t("verview","pane");
x.t("page","overview");
x.t("pane","features");
x.t("pane","provides");
x.t("molecular","analysis");
x.t("analysis","portal");
x.t("resources","available");
}
