function  WWHBookData_Files(P)
{
P.fA("Cancer Molecular Analysis Portal Online Help","Welcome.1.1.html");
P.fA("Using the Online Help","Welcome.1.2.html");
P.fA("Using Navigation Tools","Welcome.1.3.html");
P.fA("Getting Started With the Cancer Molecular Analysis Portal","cmapGetStarted.2.1.html");
P.fA("About the Cancer Molecular Analysis Portal","cmapGetStarted.2.2.html");
P.fA("Requesting a Username and Password","cmapGetStarted.2.3.html");
P.fA("Logging In to the Cancer Molecular Analysis Portal","cmapGetStarted.2.4.html");
P.fA("Navigating the Cancer Molecular Analysis Portal","cmapGetStarted.2.5.html");
P.fA("Navigating the Cancer Molecular Analysis Portal Home Page","cmapGetStarted.2.6.html");
P.fA("Navigation Pane Links","cmapGetStarted.2.7.html");
P.fA("Overview Pane Features","cmapGetStarted.2.8.html");
P.fA("User Access Pane Features","cmapGetStarted.2.9.html");
P.fA("Navigating the Cancer Molecular Analysis Portal Workspaces","cmapGetStarted.2.10.html");
P.fA("Tabs Features","cmapGetStarted.2.11.html");
P.fA("Side Bar Features","cmapGetStarted.2.12.html");
P.fA("Accessing TCGA Data","cmapGetStarted.2.13.html");
P.fA("Installing the SVG Plugin","cmapGetStarted.2.14.html");
P.fA("Logging Out","cmapGetStarted.2.15.html");
P.fA("Working With Gene-Based Views","cmapGeneView.3.1.html");
P.fA("Overview","cmapGeneView.3.2.html");
P.fA("Creating Gene Expression Plots","cmapGeneView.3.3.html");
P.fA("Understanding Geometric Mean Gene Expression Plots","cmapGeneView.3.4.html");
P.fA("Visualizing Probe Sets In the Legend","cmapGeneView.3.5.html");
P.fA("Log2 Intensity Gene Expression Plot Details","cmapGeneView.3.6.html");
P.fA("Box and Whisker Log2 Intensity Gene Expression Plot Details","cmapGeneView.3.7.html");
P.fA("Displaying Coin Plots","cmapGeneView.3.8.html");
P.fA("Creating Gene Expression-Based Kaplan-Meier Plots","cmapGeneView.3.9.html");
P.fA("Understanding Gene Expression-Based Kaplan-Meier Plots","cmapGeneView.3.10.html");
P.fA("Creating and Filtering Gene Expression Queries","cmapGeneView.3.11.html");
P.fA("Viewing Clinical Reports","cmapGeneView.3.12.html");
P.fA("Viewing Mutation and Copy Number Changes","cmapGeneView.3.13.html");
P.fA("Visualizing Pathways","cmapGeneView.3.14.html");
P.fA("Working With Pathways and Associated Anomalies","cmapPWAnom.4.1.html");
P.fA("Pathway Visualization Overview","cmapPWAnom.4.2.html");
P.fA("Generating Pathway Diagrams","cmapPWAnom.4.3.html");
P.fA("Investigating Genes Via Pathway Diagrams","cmapPWAnom.4.4.html");
P.fA("Investigating Genes Via Pathway Gene Anomalies Tables","cmapPWAnom.4.5.html");
P.fA("Navigating the Gene Anomalies Table","cmapPWAnom.4.6.html");
P.fA("Working With Genome Views","cmapGenomeView.5.1.html");
P.fA("About Genomic Views of Data","cmapGenomeView.5.2.html");
P.fA("Launching and Navigating the Heatmap Viewer","cmapGenomeView.5.3.html");
P.fA("Viewing Copy Number Data","cmapGenomeView.5.4.html");
P.fA("Viewing Gene Expression Data","cmapGenomeView.5.5.html");
P.fA("Viewing Methylation Data","cmapGenomeView.5.6.html");
P.fA("Viewing Mutation Data","cmapGenomeView.5.7.html");
P.fA("Working With Clinical Views","cmapClinicalView.6.1.html");
P.fA("Specifying Clinical Data Search Criteria","cmapClinicalView.6.2.html");
P.fA("Searching for TCGA Clinical Data","cmapClinicalView.6.3.html");
P.fA("Searching Open-Access TCGA Data","cmapClinicalView.6.4.html");
P.fA("Searching Controlled-Access TCGA Data","cmapClinicalView.6.5.html");
P.fA("Searching for REMBRANDT Clinical Data","cmapClinicalView.6.6.html");
P.fA("Navigating to the Query Results Page","cmapClinicalView.6.7.html");
P.fA("Working With Clinical Reports","cmapClinicalView.6.8.html");
P.fA("Navigating Clinical Report Table Results","cmapClinicalView.6.9.html");
P.fA("Creating Sample-Based KM Plots","cmapClinicalView.6.10.html");
P.fA("Understanding Sample-Based KM Plots","cmapClinicalView.6.11.html");
P.fA("Analysis Tools","cmapAnalysisTools.7.1.html");
P.fA("Overview","cmapAnalysisTools.7.2.html");
P.fA("Principal Component Analysis","cmapAnalysisTools.7.3.html");
P.fA("Selecting Search Criteria for Principal Component Analysis","cmapAnalysisTools.7.4.html");
P.fA("Working With PCA Plots","cmapAnalysisTools.7.5.html");
P.fA("Changing the PCA Display","cmapAnalysisTools.7.6.html");
P.fA("Selecting and Saving Samples in PCA Plots","cmapAnalysisTools.7.7.html");
P.fA("Gene Pattern Analysis","cmapAnalysisTools.7.8.html");
P.fA("Selecting Criteria for Gene Pattern Analysis","cmapAnalysisTools.7.9.html");
P.fA("GenePattern Home","cmapAnalysisTools.7.10.html");
P.fA("Integrated Heatmap Viewer","cmapAnalysisTools.7.11.html");
P.fA("Cancer Genome Workbench","cmapAnalysisTools.7.12.html");
P.fA("Managing Lists","cmapLists.8.1.html");
P.fA("List Management Overview","cmapLists.8.2.html");
P.fA("List Types","cmapLists.8.3.html");
P.fA("About PatientDID Lists","cmapLists.8.4.html");
P.fA("About Gene Lists","cmapLists.8.5.html");
P.fA("About Reporter Gene Lists","cmapLists.8.6.html");
P.fA("Viewing and Managing Lists","cmapLists.8.7.html");
P.fA("Viewing List Details","cmapLists.8.8.html");
P.fA("Viewing List Creation Data and Notes","cmapLists.8.9.html");
P.fA("Deleting Lists","cmapLists.8.10.html");
P.fA("Deleting Items From a List","cmapLists.8.11.html");
P.fA("Creating Custom Lists","cmapLists.8.12.html");
P.fA("Glossary","cmaPortalGlossary.9.1.html");
P.fA("Application Support","Application%20Support.10.1.html");
}
